spring:
  batch:
    job:
      enabled: false  # BatchTestDataInsert만 실행하고 싶으므로 배치 Job은 비활성화
    jdbc:
      initialize-schema: never
  config:
    import: classpath:application-persistence-dev.yml

# 데이터 삽입 설정
data-insert:
  user-count: ${USER_COUNT:1000}
  post-count: ${POST_COUNT:100000}
  image-count: ${IMAGE_COUNT:0}
  like-count: ${LIKE_COUNT:500000}
  comment-count: ${COMMENT_COUNT:300000}
  comment-like-count: ${COMMENT_LIKE_COUNT:100000}

logging:
  level:
    com.threadly: DEBUG
    org.springframework.batch: INFO