spring:
  batch:
    job:
      enabled: false  # BatchTestDataInsert만 실행하고 싶으므로 배치 Job은 비활성화
    jdbc:
      initialize-schema: never
  config:
    import: classpath:application-persistence-dev.yml

# 데이터 삽입 설정
data-insert:
  user-count: ${USER_COUNT:20000}
  post-count: ${POST_COUNT:500000}
  post-status: ${POST_STATUS:ACTIVE}
  image-count: ${IMAGE_COUNT:0}
  like-count: ${LIKE_COUNT:3000000}
  comment-count: ${COMMENT_COUNT:2000000}
  comment-like-count: ${COMMENT_LIKE_COUNT:0}

logging:
  level:
    com.threadly: DEBUG
    org.springframework.batch: INFO
