jwt:
  enabled: true
  secret: ${JWT.SECRET}
app:
  version: ${APP_VERSION:unknown}
ttl:
  enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
  metrics:
    tags:
      application: threadly-service
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

resilience4j:
  retry:
    instances:
      kafka-notification:
        max-attempts: 3
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.apache.kafka.common.errors.TimeoutException
          - org.springframework.kafka.KafkaException
          - com.threadly.adapter.kafka.exception.KafkaPublishException
        ignore-exceptions:
          - java.lang.IllegalArgumentException



