name: Notify on Workflow Failure

on:
  workflow_run:
    workflows: [ "CI", "CD" ]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Slack ì•Œë¦¼ ì „ì†¡
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_FAIL_WEBHOOK_URL }}
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
          WORKFLOW_URL="${{ github.event.workflow_run.html_url }}"
          
          message="âš ï¸ ì›Œí¬í”Œë¡œìš° \"$WORKFLOW_NAME\" ì´(ê°€) ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤.\nğŸ”— <$WORKFLOW_URL|ì‹¤íŒ¨ ë‚´ì—­ ë³´ëŸ¬ê°€ê¸°>"
          
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$message\"}" \
            "$SLACK_WEBHOOK_URL"