name: Notify on Workflow Success

on:
  workflow_run:
    workflows: [ "CI", "CD" ]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Slack ì•Œë¦¼ ì „ì†¡
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_FAIL_WEBHOOK_URL }}
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
          WORKFLOW_URL="${{ github.event.workflow_run.html_url }}"
          
          message="âœ… ì›Œí¬í”Œë¡œìš° \"$WORKFLOW_NAME\" ì´(ê°€) ì„±ê³µí–ˆìŠµë‹ˆë‹¤.
          ğŸ”— <$WORKFLOW_URL|ì„±ê³µ ë‚´ì—­ ë³´ëŸ¬ê°€ê¸°>"
          
           json=$(jq -nc --arg msg "$message" '{ text: $msg }')

          curl -X POST -H 'Content-type: application/json' \
            --data "$json" \
            "$SLACK_WEBHOOK_URL"
