name: Notify on PR Open

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: PR ìƒì„± ì‹œ Slack ì•Œë¦¼
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_FAIL_WEBHOOK_URL }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          message="ğŸ“Œ *ìƒˆ Pull Request ì•Œë¦¼!*
          *ì‘ì„±ì:* $PR_AUTHOR
          *ì œëª©:* $PR_TITLE
          ğŸ”— <$PR_URL|PR ë°”ë¡œ ê°€ê¸°>"
          
           json=$(jq -nc --arg msg "$message" '{ text: $msg }')

          curl -X POST -H 'Content-type: application/json' \
            --data "$json" \
            "$SLACK_WEBHOOK_URL"