name: Notify on PR Open

on:
  pull_request:
    types: [ opened ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: ìŠ¬ë™ ì›¹í›… ì •ë³´ ì„¤ì •
        run: |
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_PR_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: PR ìƒì„± ì‹œ Slack ì•Œë¦¼
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          message="ğŸ“Œ *ìƒˆ Pull Request ì•Œë¦¼!*\n*ì‘ì„±ì:* $PR_AUTHOR\n*ì œëª©:* $PR_TITLE
          ğŸ”— <$PR_URL|PR ë°”ë¡œ ê°€ê¸°>"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$message\"}" \
            "$SLACK_WEBHOOK_URL"